import React from 'react';
import { Columns, MinusCircle, PlusCircle, FileCode, CheckSquare, Layers } from 'lucide-react';
import { PipelineEvent } from '../../types/event';

interface FeaturePlanTabProps {
  events: PipelineEvent[];
}

export const FeaturePlanTab: React.FC<FeaturePlanTabProps> = ({ events }) => {
  // Find feature_plan from latest feature approval or features_agent event
  let featurePlan: any = null;
  for (let i = events.length - 1; i >= 0; i--) {
    const ev = events[i];
    if (ev.feature_plan) {
      featurePlan = ev.feature_plan;
      break;
    }
    if (ev.plan && typeof ev.plan === 'object') {
      featurePlan = ev.plan;
      break;
    }
  }

  // Locate acknowledged operator modification instructions if any
  let modificationsText = '';
  for (let i = events.length - 1; i >= 0; i--) {
    const ev = events[i];
    if (ev.event_type === 'operator_modification_acknowledged' && ev.modifications) {
      modificationsText = ev.modifications;
      break;
    }
    if (ev.modifications && typeof ev.modifications === 'string') {
      modificationsText = ev.modifications;
      break;
    }
  }
  if (!modificationsText && featurePlan?.modifications) {
    modificationsText = featurePlan.modifications;
  }

  const diff = featurePlan?.structural_diff || {};
  const droppedColumns = diff.dropped_columns || [];
  const addedColumns = diff.added_columns || [];
  const rowDelta = diff.row_delta ?? diff.row_count_delta;
  const nullDelta = diff.null_count_delta;

  return (
    <div className="p-5 space-y-6 overflow-y-auto max-h-full bg-[#FAF9F5] dark:bg-[#090D16] min-h-full text-stone-900 dark:text-slate-100 transition-colors">
      <div>
        <h3 className="text-sm font-semibold text-stone-900 dark:text-slate-100">Feature Engineering &amp; Approval Plan</h3>
        <p className="text-xs text-stone-500 dark:text-slate-400">
          Structural schema diff and code transformations generated by the Features Agent.
        </p>
      </div>

      {!featurePlan ? (
        <div className="p-8 text-center bg-white dark:bg-slate-900 border border-[#E8E6DF] dark:border-slate-800 rounded-xl shadow-xs">
          <Layers className="w-8 h-8 text-stone-300 dark:text-slate-600 mx-auto mb-2" />
          <p className="text-xs text-stone-500 dark:text-slate-400">No feature transformation plan found in current run events.</p>
        </div>
      ) : (
        <div className="space-y-5">
          {/* Operator Modifications Card if present */}
          {modificationsText && (
            <div className="bg-amber-50/70 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-800 rounded-xl p-4 space-y-1.5 shadow-xs">
              <div className="flex items-center space-x-2">
                <CheckSquare className="w-4 h-4 text-amber-700 dark:text-amber-400" />
                <h4 className="text-xs font-semibold uppercase tracking-wider text-amber-800 dark:text-amber-300">
                  Acknowledged Operator Instructions
                </h4>
              </div>
              <p className="text-xs text-amber-900 dark:text-amber-200 leading-relaxed font-mono whitespace-pre-wrap">
                {modificationsText}
              </p>
            </div>
          )}

          {/* Summary Card */}
          <div className="bg-white dark:bg-slate-900 border border-[#E8E6DF] dark:border-slate-800 rounded-xl p-4 space-y-2 shadow-xs">
            <h4 className="text-xs font-semibold uppercase tracking-wider text-violet-700 dark:text-violet-400">
              Plan Description
            </h4>
            <p className="text-xs text-stone-800 dark:text-slate-200 leading-relaxed">
              {featurePlan.description || 'Feature engineering modification proposed.'}
            </p>
            {featurePlan.proposed_output_path && (
              <p className="text-[11px] font-mono text-stone-500 dark:text-slate-400 pt-1">
                Target Output: <span className="text-stone-800 dark:text-slate-200 font-medium">{featurePlan.proposed_output_path}</span>
              </p>
            )}
          </div>

          {/* Structural Diff Card */}
          <div className="bg-white dark:bg-slate-900 border border-[#E8E6DF] dark:border-slate-800 rounded-xl p-4 space-y-4 shadow-xs">
            <div className="flex items-center justify-between border-b border-[#E8E6DF] dark:border-slate-800 pb-2.5">
              <div className="flex items-center space-x-2">
                <Columns className="w-4 h-4 text-violet-600 dark:text-violet-400" />
                <h4 className="text-xs font-semibold uppercase tracking-wider text-stone-800 dark:text-slate-200">
                  Structural Schema Diff
                </h4>
              </div>
              <div className="flex items-center space-x-3 text-xs font-mono">
                {rowDelta !== undefined && (
                  <span className={rowDelta < 0 ? 'text-rose-600 dark:text-rose-400' : 'text-stone-700 dark:text-slate-300'}>
                    Row Delta: {rowDelta > 0 ? `+${rowDelta}` : rowDelta}
                  </span>
                )}
                {nullDelta !== undefined && (
                  <span className="text-stone-700 dark:text-slate-300">
                    Nulls Delta: {nullDelta > 0 ? `+${nullDelta}` : nullDelta}
                  </span>
                )}
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Dropped Columns */}
              <div className="bg-[#FAF9F5] dark:bg-slate-950 p-3 rounded-lg border border-[#E8E6DF] dark:border-slate-800 space-y-2">
                <div className="flex items-center space-x-1.5 text-xs font-medium text-rose-700 dark:text-rose-400">
                  <MinusCircle className="w-3.5 h-3.5" />
                  <span>Dropped Columns ({droppedColumns.length})</span>
                </div>
                {droppedColumns.length === 0 ? (
                  <p className="text-[11px] text-stone-400 dark:text-slate-500 italic">No columns dropped.</p>
                ) : (
                  <div className="flex flex-wrap gap-1.5">
                    {droppedColumns.map((col: string) => (
                      <span
                        key={col}
                        className="px-2 py-0.5 rounded-full bg-rose-50 dark:bg-rose-950/60 border border-rose-200 dark:border-rose-900 text-rose-700 dark:text-rose-300 font-mono text-[11px]"
                      >
                        {col}
                      </span>
                    ))}
                  </div>
                )}
              </div>

              {/* Added Columns */}
              <div className="bg-[#FAF9F5] dark:bg-slate-950 p-3 rounded-lg border border-[#E8E6DF] dark:border-slate-800 space-y-2">
                <div className="flex items-center space-x-1.5 text-xs font-medium text-emerald-700 dark:text-emerald-400">
                  <PlusCircle className="w-3.5 h-3.5" />
                  <span>Added Features ({addedColumns.length})</span>
                </div>
                {addedColumns.length === 0 ? (
                  <p className="text-[11px] text-stone-400 dark:text-slate-500 italic">No columns added.</p>
                ) : (
                  <div className="flex flex-wrap gap-1.5">
                    {addedColumns.map((col: string) => (
                      <span
                        key={col}
                        className="px-2 py-0.5 rounded-full bg-emerald-50 dark:bg-emerald-950/60 border border-emerald-200 dark:border-emerald-900 text-emerald-700 dark:text-emerald-300 font-mono text-[11px]"
                      >
                        +{col}
                      </span>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Generated Code Preview */}
          {featurePlan.code && (
            <div className="bg-white dark:bg-slate-900 border border-[#E8E6DF] dark:border-slate-800 rounded-xl p-4 space-y-2 shadow-xs">
              <div className="flex items-center space-x-2 pb-2 border-b border-[#E8E6DF] dark:border-slate-800">
                <FileCode className="w-4 h-4 text-violet-600 dark:text-violet-400" />
                <h4 className="text-xs font-semibold uppercase tracking-wider text-stone-800 dark:text-slate-200">
                  Transformation Code
                </h4>
              </div>
              <pre className="p-3 bg-[#F5F4EE] dark:bg-slate-950 rounded-lg text-xs font-mono text-stone-800 dark:text-emerald-300 overflow-x-auto border border-[#E8E6DF] dark:border-slate-800 leading-relaxed">
                <code>{featurePlan.code}</code>
              </pre>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
