import React from 'react';
import { Columns, MinusCircle, PlusCircle, FileCode, CheckSquare, Layers } from 'lucide-react';
import { PipelineEvent } from '../../types/event';

interface FeaturePlanTabProps {
  events: PipelineEvent[];
}

export const FeaturePlanTab: React.FC<FeaturePlanTabProps> = ({ events }) => {
  // Find feature_plan from latest feature approval or features_agent event
  let featurePlan: any = null;
  for (let i = events.length - 1; i >= 0; i--) {
    const ev = events[i];
    if (ev.feature_plan) {
      featurePlan = ev.feature_plan;
      break;
    }
    if (ev.plan && typeof ev.plan === 'object') {
      featurePlan = ev.plan;
      break;
    }
  }

  const diff = featurePlan?.structural_diff || {};
  const droppedColumns = diff.dropped_columns || [];
  const addedColumns = diff.added_columns || [];
  const rowDelta = diff.row_count_delta;
  const nullDelta = diff.null_count_delta;

  return (
    <div className="p-5 space-y-6 overflow-y-auto max-h-full">
      <div>
        <h3 className="text-sm font-semibold text-slate-200">Feature Engineering & Approval Plan</h3>
        <p className="text-xs text-slate-400">
          Structural schema diff and code transformations generated by the Features Agent.
        </p>
      </div>

      {!featurePlan ? (
        <div className="p-8 text-center bg-slate-950/40 border border-slate-800 rounded-xl">
          <Layers className="w-8 h-8 text-slate-400 mx-auto mb-2 opacity-50" />
          <p className="text-xs text-slate-400">No feature transformation plan found in current run events.</p>
        </div>
      ) : (
        <div className="space-y-5">
          {/* Summary Card */}
          <div className="bg-slate-900/70 border border-slate-800 rounded-xl p-4 space-y-2">
            <h4 className="text-xs font-semibold uppercase tracking-wider text-indigo-400">
              Plan Description
            </h4>
            <p className="text-xs text-slate-200 leading-relaxed">
              {featurePlan.description || 'Feature engineering modification proposed.'}
            </p>
            {featurePlan.proposed_output_path && (
              <p className="text-[11px] font-mono text-slate-400 pt-1">
                Target Output: <span className="text-slate-300">{featurePlan.proposed_output_path}</span>
              </p>
            )}
          </div>

          {/* Structural Diff Card */}
          <div className="bg-slate-900/70 border border-slate-800 rounded-xl p-4 space-y-4">
            <div className="flex items-center justify-between border-b border-slate-800 pb-2.5">
              <div className="flex items-center space-x-2">
                <Columns className="w-4 h-4 text-cyan-400" />
                <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-200">
                  Structural Schema Diff
                </h4>
              </div>
              <div className="flex items-center space-x-3 text-xs font-mono">
                {rowDelta !== undefined && (
                  <span className={rowDelta < 0 ? 'text-rose-400' : 'text-slate-300'}>
                    Row Delta: {rowDelta > 0 ? `+${rowDelta}` : rowDelta}
                  </span>
                )}
                {nullDelta !== undefined && (
                  <span className="text-slate-300">
                    Nulls Delta: {nullDelta > 0 ? `+${nullDelta}` : nullDelta}
                  </span>
                )}
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Dropped Columns */}
              <div className="bg-slate-950/60 p-3 rounded-lg border border-slate-800/80 space-y-2">
                <div className="flex items-center space-x-1.5 text-xs font-medium text-rose-400">
                  <MinusCircle className="w-3.5 h-3.5" />
                  <span>Dropped Columns ({droppedColumns.length})</span>
                </div>
                {droppedColumns.length === 0 ? (
                  <p className="text-[11px] text-slate-400 italic">No columns dropped.</p>
                ) : (
                  <div className="flex flex-wrap gap-1.5">
                    {droppedColumns.map((col: string) => (
                      <span
                        key={col}
                        className="px-2 py-0.5 rounded bg-rose-950/70 border border-rose-500/40 text-rose-300 font-mono text-[11px]"
                      >
                        {col}
                      </span>
                    ))}
                  </div>
                )}
              </div>

              {/* Added Columns */}
              <div className="bg-slate-950/60 p-3 rounded-lg border border-slate-800/80 space-y-2">
                <div className="flex items-center space-x-1.5 text-xs font-medium text-emerald-400">
                  <PlusCircle className="w-3.5 h-3.5" />
                  <span>Added Features ({addedColumns.length})</span>
                </div>
                {addedColumns.length === 0 ? (
                  <p className="text-[11px] text-slate-400 italic">No columns added.</p>
                ) : (
                  <div className="flex flex-wrap gap-1.5">
                    {addedColumns.map((col: string) => (
                      <span
                        key={col}
                        className="px-2 py-0.5 rounded bg-emerald-950/70 border border-emerald-500/40 text-emerald-300 font-mono text-[11px]"
                      >
                        +{col}
                      </span>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Generated Code Preview */}
          {featurePlan.code && (
            <div className="bg-slate-900/70 border border-slate-800 rounded-xl p-4 space-y-2">
              <div className="flex items-center space-x-2 pb-2 border-b border-slate-800">
                <FileCode className="w-4 h-4 text-indigo-400" />
                <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-200">
                  Transformation Code
                </h4>
              </div>
              <pre className="p-3 bg-slate-950 rounded-lg text-xs font-mono text-slate-300 overflow-x-auto border border-slate-800/80 leading-relaxed">
                <code>{featurePlan.code}</code>
              </pre>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
