import React from 'react';
import { FileText, Download, CheckCircle, Clock } from 'lucide-react';
import { PipelineEvent } from '../../types/event';
import { PipelineRun } from '../../types/run';
import { formatScore, formatDuration, formatCost } from '../../utils/formatters';

interface ReportTabProps {
  run: PipelineRun;
  events: PipelineEvent[];
}

export const ReportTab: React.FC<ReportTabProps> = ({ run, events }) => {
  // Locate report text from run record first (persisted without truncation), then fallback to events
  let reportText = run.report || '';
  if (!reportText) {
    for (let i = events.length - 1; i >= 0; i--) {
      const ev = events[i];
      if (ev.agent === 'reporter_agent' && (ev.report || ev.text || ev.content)) {
        reportText = ev.report || ev.text || ev.content;
        break;
      }
    }
  }

  return (
    <div className="p-5 space-y-6 overflow-y-auto max-h-full bg-[#FAF9F5] dark:bg-[#090D16] min-h-full text-stone-900 dark:text-slate-100 transition-colors">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-sm font-semibold text-stone-900 dark:text-slate-100">Executive Pipeline Report</h3>
          <p className="text-xs text-stone-500 dark:text-slate-400">
            Synthesized final report generated by the Reporter Agent upon pipeline completion.
          </p>
        </div>
        {run.report_path && (
          <div className="text-[11px] font-mono text-stone-500 dark:text-slate-400 bg-stone-50 dark:bg-slate-800 border border-stone-200 dark:border-slate-700 px-2.5 py-1 rounded-md">
            Artifact: <span className="text-stone-800 dark:text-slate-200 font-medium">{run.report_path}</span>
          </div>
        )}
      </div>

      {/* Summary KPI Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className="bg-white dark:bg-slate-900 border border-[#E8E6DF] dark:border-slate-800 p-3.5 rounded-xl shadow-xs">
          <span className="text-[11px] text-stone-500 dark:text-slate-400 font-medium">Winning Metric</span>
          <p className="text-lg font-bold font-mono text-emerald-700 dark:text-emerald-400 mt-0.5">
            {formatScore(run.best_score)}
          </p>
        </div>
        <div className="bg-white dark:bg-slate-900 border border-[#E8E6DF] dark:border-slate-800 p-3.5 rounded-xl shadow-xs">
          <span className="text-[11px] text-stone-500 dark:text-slate-400 font-medium">Total Attempts</span>
          <p className="text-lg font-bold font-mono text-stone-900 dark:text-slate-100 mt-0.5">
            {run.total_attempts}
          </p>
        </div>
        <div className="bg-white dark:bg-slate-900 border border-[#E8E6DF] dark:border-slate-800 p-3.5 rounded-xl shadow-xs">
          <span className="text-[11px] text-stone-500 dark:text-slate-400 font-medium">Total Duration</span>
          <p className="text-lg font-bold font-mono text-stone-900 dark:text-slate-100 mt-0.5">
            {formatDuration(run.duration_s)}
          </p>
        </div>
        <div className="bg-white dark:bg-slate-900 border border-[#E8E6DF] dark:border-slate-800 p-3.5 rounded-xl shadow-xs">
          <span className="text-[11px] text-stone-500 dark:text-slate-400 font-medium">Compute Cost</span>
          <p className="text-lg font-bold font-mono text-stone-900 dark:text-slate-100 mt-0.5">
            {formatCost(run.total_cost_usd)}
          </p>
        </div>
      </div>

      {/* Report Content Body */}
      {!reportText ? (
        <div className="p-10 text-center bg-white dark:bg-slate-900 border border-[#E8E6DF] dark:border-slate-800 rounded-xl shadow-xs space-y-2">
          <FileText className="w-8 h-8 text-stone-300 dark:text-slate-600 mx-auto" />
          <p className="text-xs text-stone-500 dark:text-slate-400">
            {run.status === 'running'
              ? 'The pipeline is still executing. The final report will be generated when the Reporter agent runs.'
              : 'No final report text artifact was found for this run.'}
          </p>
        </div>
      ) : (
        <div className="bg-white dark:bg-slate-900 border border-[#E8E6DF] dark:border-slate-800 rounded-xl p-6 shadow-xs">
          <article className="max-w-none text-xs leading-relaxed space-y-4">
            <div className="whitespace-pre-wrap font-sans text-stone-800 dark:text-slate-200 text-xs leading-6">
              {reportText}
            </div>
          </article>
        </div>
      )}
    </div>
  );
};
