import React from 'react';
import { FileText, Download, CheckCircle, Clock } from 'lucide-react';
import { PipelineEvent } from '../../types/event';
import { PipelineRun } from '../../types/run';
import { formatScore, formatDuration, formatCost } from '../../utils/formatters';

interface ReportTabProps {
  run: PipelineRun;
  events: PipelineEvent[];
}

export const ReportTab: React.FC<ReportTabProps> = ({ run, events }) => {
  // Locate report text from events (e.g. reporter_agent event or text stream)
  let reportText = '';
  for (let i = events.length - 1; i >= 0; i--) {
    const ev = events[i];
    if (ev.agent === 'reporter_agent' && (ev.report || ev.text || ev.content)) {
      reportText = ev.report || ev.text || ev.content;
      break;
    }
  }

  return (
    <div className="p-5 space-y-6 overflow-y-auto max-h-full">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-sm font-semibold text-slate-200">Executive Pipeline Report</h3>
          <p className="text-xs text-slate-400">
            Synthesized final report generated by the Reporter Agent upon pipeline completion.
          </p>
        </div>
      </div>

      {/* Summary KPI Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className="bg-slate-900/70 border border-slate-800 p-3 rounded-lg">
          <span className="text-[11px] text-slate-400">Winning Metric</span>
          <p className="text-base font-bold font-mono text-emerald-400 mt-0.5">
            {formatScore(run.best_score)}
          </p>
        </div>
        <div className="bg-slate-900/70 border border-slate-800 p-3 rounded-lg">
          <span className="text-[11px] text-slate-400">Total Attempts</span>
          <p className="text-base font-bold font-mono text-slate-200 mt-0.5">
            {run.total_attempts}
          </p>
        </div>
        <div className="bg-slate-900/70 border border-slate-800 p-3 rounded-lg">
          <span className="text-[11px] text-slate-400">Total Duration</span>
          <p className="text-base font-bold font-mono text-slate-200 mt-0.5">
            {formatDuration(run.duration_s)}
          </p>
        </div>
        <div className="bg-slate-900/70 border border-slate-800 p-3 rounded-lg">
          <span className="text-[11px] text-slate-400">Compute Cost</span>
          <p className="text-base font-bold font-mono text-slate-200 mt-0.5">
            {formatCost(run.total_cost_usd)}
          </p>
        </div>
      </div>

      {/* Report Content Body */}
      {!reportText ? (
        <div className="p-10 text-center bg-slate-950/40 border border-slate-800 rounded-xl space-y-2">
          <FileText className="w-8 h-8 text-slate-400 mx-auto opacity-50" />
          <p className="text-xs text-slate-400">
            {run.status === 'running'
              ? 'The pipeline is still executing. The final report will be generated when the Reporter agent runs.'
              : 'No final report text artifact was found for this run.'}
          </p>
        </div>
      ) : (
        <div className="bg-slate-900/70 border border-slate-800 rounded-xl p-6 shadow-sm">
          <article className="prose prose-invert prose-slate max-w-none text-xs leading-relaxed space-y-4">
            <div className="whitespace-pre-wrap font-sans text-slate-200 text-xs leading-6">
              {reportText}
            </div>
          </article>
        </div>
      )}
    </div>
  );
};
